### ISSUE TITLE
Is it ready to use?

### ISSUE THREAD

**Issue by acelot** [phug-php/renderer#1]
Can I use Phug for production or I should stay on pug-php?

**Comment by kylekatarnls** [comment]
Hi, no sorry, we cannot say that. Phug is about half ready. Our goal is to match pugjs specifications then implement extensions dedicated to PHP. For now, we pass 36% of the pugjs unit tests. This means you lack many features in using Phug such as `yield` or dynamic mixins.

**Comment by kylekatarnls** [comment]
Hi, 100% reached, we will soon publish a candidate release of Phug. Also pug-demo. So you can start to implement it in your project. I will also soon publish a branch 3.0.x for preparing pug-php 3.0 that will use Phug but keep a API close from pug-php 2.0.

**Comment by kylekatarnls** [comment]
Hi, issues in phug-php/renderer will soon be closed to centralize all issues in phug-php/puhg.

So this issue will disappear. If you need something, please go to https://github.com/phug-php/phug/issues

About the renderer, you can use it, just be aware, we run into trouble for recursive mixins (we discover lately because it's not part of the pugjs unit tests). So we need to refactorize a lot our mixin system in phug and it will postpone the release but it should not cause breaking changes. If you do not have recursive mixins, you should be able to use the renderer as it safely.
